### ISSUE TITLE
Ability to write "columns of comments" to the right of data columns

### ISSUE THREAD

**Issue by heidikira** [startable/startables-python#4]
When writing a StarTable file, some applications require that extra columns be written to the right of a table, separated by an empty column -- such that these extra columns are, in effect, comments that are not to be read-in by subsequent tools. These extra columns are typically for human QA, and having them as comments (rather than actual machine-readable data columns) mean that their format can be more flexible. 

It would be great to have a way to include such "comment columns" in Table objects, and have the writer write them to file. 

Eg;

```
**myTable
myDestination
height | M   | Q  | T   |   | Eg_M | Eg_Q | Eg_T | height_seabed
m      | kNm | kN | kNm |   | text | text | text | m
10     | 29  | 18 | 20  |   | 1.2  | 6.2a | 1.2  | 52
0      | 28  | 18 | 20  |   | 1.2  | 6.2a | 1.2  | 42

                         ^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                         sep       comment columns
```

Note that the comment rows may not necessarily just be text, and may also contain a unit.

Therefore, a way to indicate which columns are 'comments' or 'extra data' are needed.

**Comment by jfcorbett** [comment]
After some discussion: Cost/benefit of this isn't clear enough to proceed for now. 
Can reopen later if more demand.
